name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install Fyne
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest
        
    - name: Build Windows
      run: |
        cd cmd/gui
        go build -ldflags="-H windowsgui" -o FolderToGit.exe
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: FolderToGit-Windows
        path: cmd/gui/FolderToGit.exe 